name: Integration Tests

on: [push]

jobs:
  unit-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.25.x' ]

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Integration Tests
        run: make itest
